FROM python:3.10-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Gunicorn will read $PORT from the environment that Cloud Run sets
CMD ["gunicorn", "-b", "0.0.0.0:$PORT", "main:app"]
